#!/usr/bin/env bash
# CustomPiOS module : openmower
# <Description what this module does>
# Written by DocGalaxyBlock (https://github.com/docgalaxyblock/)
# GPL V3
########

# Source error handling, leave this in place
set -ex

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap


echo_green "Copying files to root filesystem and applying permissions..."
unpack /filesystem/root /

echo_green "Cloning OpenMowerOS-Tools..."
git clone https://github.com/ClemensElflein/OMIAUH /home/pi/openmoweros-tools
chown -R pi:pi /home/pi

cp /boot/openmower/hotspot.txt /boot/openmower/hotspot-example.txt

echo_green "Get the latest releases-beta mower_config.sh example..."
wget -O /boot/openmower/mower_config.txt https://github.com/ClemensElflein/open_mower_ros/raw/releases/beta/src/open_mower/config/mower_config.sh.example

# replace default comitup modules configs and paths
echo_green "Replace comitup path and config..."
sed -i 's|/boot/comitup.conf|/boot/openmower/hotspot.txt|g ; s|/boot/comitup.conf.settings-applied|/boot/openmower/hotspot.settings-applied|' /etc/systemd/system/comitup_config_copy.service

# ensure conflicting services are masked
echo_green "ensure comitup/NetworkManager conflicting servies are masked..."
systemctl_if_exists mask dhcpd.service
systemctl_if_exists mask dhcpcd.service
systemctl_if_exists mask wpa-supplicant.service
systemctl_if_exists mask raspberrypi-net-mods.service
systemctl_if_exists mask hciuart.service

echo_green "Get some debugging tools..."
apt-get update --allow-releaseinfo-change
apt-get install --yes tmux screen minicom socat

echo_green "Disabling podman socket..."
systemctl disable podman.socket

echo_green "Disabling podman auto update..."
systemctl disable podman-auto-update.timer podman-auto-update.service 

echo_green "Installing mosquitto and masking the normal mosquitto.service..."
apt-get install --yes mosquitto
systemctl_if_exists mask mosquitto.service

echo_green "Setting startup rules for openmower services..."
systemctl enable openmower.service
systemctl disable openmower-debug.service
systemctl disable openmower-mqtt-bridge.service


#cleanup
apt-get clean
apt-get autoremove --yes
